### ISSUE TITLE
Documentation sub reports

### ISSUE THREAD

**Issue by jadsonbr** [PyReportJasper/pyreportjasper#19]
Put in documentation how to use sub reports

**Comment by jadsonbr** [comment]
Done.

https://github.com/PyReportJasper/pyreportjasper#subreport-example

**Comment by 1orZero** [comment]
The Subreport Example is no longer there...

**Comment by jadsonbr** [comment]
Hello @1orZero, thanks for contacting us.

Below is the example link with subreport

[https://repl.it/@JadsonRibeiro/sub-report-pyreportjasper](https://repl.it/@JadsonRibeiro/sub-report-pyreportjasper)

**Comment by tyler-tj** [comment]
@jadsonbr Is the subreport example still up somewhere? Seems the repl.it is not working.

**Comment by jadsonbr** [comment]
@tyler-tj I just tested it here and it's still functional. Are there any errors there?

**Comment by tyler-tj** [comment]
@jadsonbr Just tried on my personal laptop, think I was having issues with the VPN on my work laptop on repl. 

Looks good! Just to confirm something do the main and subreports need to be compiled to .jasper before calling process_report()? And say I'm using a single JSON file as a datasource, if I specify in the .config() the single JSON file will both main and subreports be able to use it?

**Comment by jadsonbr** [comment]
@tyler-tj In the case of the example I used the .jasper in the subreport if necessary use the method to compile the others. About the data source of the surveys we set up to use the same data source as the main file.

**Comment by tyler-tj** [comment]
@jadsonbr Great, thanks for the info
