### ISSUE TITLE
JSONQL data source support

### ISSUE THREAD

**Issue by ShaheedHaque** [PyReportJasper/pyreportjasper#31]
I just filed [a request with jasperstarter](https://cenote-issues.atlassian.net/browse/JAS-113) to add JSONQL data source support. Since I driver them through pyjasper, I'd like to request the same here. I believe the change is as simple as this:

```
$ diff -U5 t.t /usr/local/lib/python3.6/dist-packages/pyjasper/jasperpy.py
--- t.t 2018-05-22 19:46:03.381854873 +0100
+++ /usr/local/lib/python3.6/dist-packages/pyjasper/jasperpy.py 2018-05-22 19:41:23.923518239 +0100
@@ -137,10 +137,13 @@
                 command += ' --data-file ' + db_connection['data_file']
 
             if 'json_query' in db_connection:
                 command += ' --json-query ' + db_connection['json_query']
 
+            if 'jsonql_query' in db_connection:
+                command += ' --jsonql-query ' + db_connection['jsonql_query']
+
         self._command = command
 
         return self.execute()
 
     @staticmethod

```

The change could even, in principle, be added in parallel with the upstream change. If needed, I'd be happy to do a PR.

**Comment by jadsonbr** [comment]
I understand perfectly, but this library is called `pyreportjasper` and I think the one you are using is the `pyjasper` that is by another author

**Comment by ShaheedHaque** [comment]
Whoops, apologies for the incorrect reference to pyjasper. I am definitely using your library: the patch noted above is to this file in this project:

https://github.com/jadsonbr/pyreportjasper/blob/master/pyreportjasper/jasperpy.py

Please do consider the request!

**Comment by jadsonbr** [comment]
feel free to send us a PR.

**Comment by jadsonbr** [comment]
Done
