### ISSUE TITLE
Get data from resource file

### ISSUE THREAD

**Issue by MANUVILAKUNNATHU** [PyReportJasper/pyreportjasper#34]
I want to set a date format from .properties(resource file) file. How to do this in pyreportjasper ?
eg:(new SimpleDateFormat($R{format.date})).format(new Date())

**Comment by Rupesh2018** [comment]
@jadsonbr @caduvieira @ShaheedHaque @mstuttgart

**Comment by jadsonbr** [comment]
@MANUVILAKUNNATHU @Rupesh2018 
If you need provide resource to report, you can do that by set parameter resource in method jasper.process

Follow the documentation link: [Doc resources](https://github.com/PyReportJasper/pyreportjasper#working-with-resources-i18n-resource-bundles-icons-or-images)

**Comment by Rupesh2018** [comment]
Can I create a Report_Resource_bundle and provide it as parameter and use it as $R{format.date}). And format.date will be available in .properties file and it will contain a date format which is to be used as format to display date

**Comment by Rupesh2018** [comment]
@jadsonbr @caduvieira @ShaheedHaque @mstuttgart @MANUVILAKUNNATHU

**Comment by jadsonbr** [comment]
Having trouble running the report?

**Comment by Rupesh2018** [comment]
Yes, The report is giving th output but date field is displayed as empty. Can you help?

**Comment by Rupesh2018** [comment]
@jadsonbr Had set value to System Parameter REPORT_RESOURCE_BUNDLE. But Getting the following error.
Parameter 'REPORT_RESOURCE_BUNDLE' of type 'java.util.ResourceBundle with value '{u'format.time2': u'hh:mm', u'format.time3': u'HH:mm:ss', u'format.date': u'dd/MM/yyyy'}' is not supported by JasperStarter!

May I know why this error occurred!
@jadsonbr @caduvieira @ShaheedHaque @mstuttgart @MANUVILAKUNNATHU

**Comment by Rupesh2018** [comment]
@jadsonbr

**Comment by Rupesh2018** [comment]
@jadsonbr @jadsonbr @caduvieira @ShaheedHaque @mstuttgart

**Comment by jadsonbr** [comment]
@Rupesh2018 
Upload your code and files in git to see what we can help

**Comment by jadsonbr** [comment]
It was resolved, please close the issue

**Comment by Rupesh2018** [comment]
Switched to other tool
