### ISSUE TITLE
Interferance with python logging

### ISSUE THREAD

**Issue by angsm** [PyReportJasper/pyreportjasper#36]
Hi, has anyone experience this python module interfering with python **logging** module? If I import "from pyreportjasper import JasperPy", my script's logging just refuses to output any logs.

**Comment by jadsoncopam** [comment]
Take a look at this line of code and see if it might be interfering with your application. Because it is used by pyreportjasper

```python
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)
```

**Comment by jadsonbr** [comment]
Can you look?

**Comment by angsm** [comment]
Yup, I tried changing my logger's name, but my logger is not logging, not sure why. Let me dig further into it.

**Comment by jadsonbr** [comment]
Done, need to upload to pypi

**Comment by jadsonbr** [comment]
Correction is in the master.
And issue closed for lack of interaction.
