### ISSUE TITLE
cStringIO is not available in python 3.x

### ISSUE THREAD

**Issue by karthikeyanPalanisamy** [PyReportJasper/pyreportjasper#37]
Please consider updating import StringIO from io for Python 3.x since cStringIO is not longer available in Python 3.x

Traceback (most recent call last):
  ...
     import pyjasper
  File "C:\Program Files\Python36\lib\site-packages\pyjasper\__init__.py", line 4, in <module>
    from pyjasper.client_subreport import JasperGeneratorWithSubreport
  File "C:\Program Files\Python36\lib\site-packages\pyjasper\client.py", line 13, in <module>
    from cStringIO import StringIO
ModuleNotFoundError: No module named 'cStringIO'

Soln:-
use 
    from io import StringIO
instead of
    from cStringIO import StringIO
for Python 3.x

**Comment by jadsonbr** [comment]
Already tested with the new version?

**Comment by karthikeyanPalanisamy** [comment]
yes, i'm using it with the change i made it in my local.

**Comment by jadsonbr** [comment]
If everything is ok, you can close the issue
