### ISSUE TITLE
Reports using subdatasets support

### ISSUE THREAD

**Issue by estebansuarez-dev** [PyReportJasper/pyreportjasper#41]
Good Evening, hope you be fine. The matter of this issue it's that I'm trying to generate a JSON file based report where I'm using a main dataset to filling the most of  it and a subdataset to filling a pie chart in the same report. Main dataset and subdataset take their data from different array atributes in the same Json object, so what I'd like to ask you is: **does the library supports working with subdataset enabled reports?** If so, I'd really appreciate if you were able to post an example on how to do it. Attached to this issue there's an example of the Json structure  I'm using as the report datasource:
[Detalle_Costos.txt](https://github.com/PyReportJasper/pyreportjasper/files/2591302/Detalle_Costos.txt)

Thanks in advance for your help

Regards:
Esteban

**Comment by jadsonbr** [comment]
Yes, the library supports subdatasets with the same data source by taking the different arrays.

You can do this by stating that the subreport has the same data source as the principal that will be your json file plus the json_query of the subreport will be **totales** that refer to the array of objects in your json file and the json_query of the main jrxml will receive the json_query **data**.


Call example:
```python
def subreport_example():
    input_file_details = os.path.dirname(os.path.abspath(__file__)) + \
        '/examples/subreports/details.jrxml'
    input_file_main = os.path.dirname(os.path.abspath(__file__)) + \
        '/examples/subreports/main.jrxml'
    input_file = os.path.dirname(os.path.abspath(__file__)) + \
        '/examples/subreports/main.jasper'
    data_file = os.path.dirname(os.path.abspath(__file__)) + \
        '/examples/subreports/detalle_costos.json'
    output = os.path.dirname(os.path.abspath(__file__)) + '/output/examples/subreports/'
    jasper = JasperPy()
    jasper.compile(input_file_details)
    jasper.compile(input_file_main)
    jasper.process(
                input_file,
                output_file=output,
                format_list=["pdf"],
                parameters={},
                db_connection={
                    'data_file': data_file,
                    'driver': 'json',
                    'json_query': 'data', # Main Dataset array
                },
                locale='pt_BR',  # LOCALE Ex.:(en_US, de_GE)
                resource='examples/subreports/'
            )
```

**Comment by jadsonbr** [comment]
Closed for lack of interaction
