### ISSUE TITLE
How to pass xml/json data source as string not as file?

### ISSUE THREAD

**Issue by pklewandowski** [PyReportJasper/pyreportjasper#43]
Hello,
I have xml data stored in database column for each document. I want to use it as data to genereate report. How can I pass it as ie. string or something but not as file.

**Comment by ShaheedHaque** [comment]
Jasperstarter 3.4, just released, exposes an API which you could use to avoid the need to use a file. The API is a Java API, but can be accessed from Python using jpy as per the [provided example](https://bitbucket.org/cenote/jasperstarter/src/master/src/test/resources/python/jasperstarter.py).

**Comment by jadsonbr** [comment]
@ShaheedHaque @pklewandowski 

I released a new version by exploring the API provided by jasperstarter. I haven't climbed to pypi yet but can already be tested by installing it through git.
I kept around 97% compatibility with current lib calls so the impact will be as little as possible.

You can follow the new version via the link [pyjasperstarter2](https://github.com/PyReportJasper/pyreportjasper2)

**Comment by jadsonbr** [comment]
@pklewandowski Has the issue been resolved?
