### ISSUE TITLE
Subprocess-less integration with jasperstarter

### ISSUE THREAD

**Issue by ShaheedHaque** [PyReportJasper/pyreportjasper#44]
Jasperstarter 3.4, just released, exposes an API which pyreportjasper could use to avoid the need to use a subprocess. The API is a Java API, but can be accessed from Python using jpy as per the [provided example](https://bitbucket.org/cenote/jasperstarter/src/master/src/test/resources/python/jasperstarter.py).

**Comment by ShaheedHaque** [comment]
You might also be interested in JasperStarter 3.5.0 which, when released, will contain the fix for  https://cenote-issues.atlassian.net/browse/JAS-131.

**Comment by jadsonbr** [comment]
@ShaheedHaque 

I released a new version by exploring the API provided by jasperstarter. I haven't climbed to pypi yet but can already be tested by installing it through git.
I kept around 97% compatibility with current lib calls so the impact will be as little as possible.

You can follow the new version via the link [pyreportjasper2](https://github.com/PyReportJasper/pyreportjasper2)

**Comment by jadsonbr** [comment]
@ShaheedHaque If resolved, please close the issue.
