### ISSUE TITLE
Getting Null as values while running jasper report using pyreport jasper and mongo

### ISSUE THREAD

**Issue by varun952** [PyReportJasper/pyreportjasper#45]
Following is my python code to run a simple report that displays records in tabular format : 
FYI I am using folllowing mongo driver : mongodb-driver-sync-3.7.1.jar

```
from pyreportjasper import JasperPy

if __name__ == '__main__':

  input_file = '/home/ubuntu1604/JaspersoftWorkspace/MyReports/my_Landscape.jasper'
    output = '/home/ubuntu1604'
    con = {
        'driver': 'none',
        'jdbc_driver': 'mongodb.jdbc.MongoDriver',
        'jdbc_url': 'jdbc:mongo://user:uset@127.0.0.1:27107/db_name',
        'port': '27107'
    }
    jasper = JasperPy()
    jasper.process(
        input_file,
        output_file=output,
        format_list=["pdf"],
        parameters={"PARAM_1":"hawkeye", "PARAM_2":"xyz"},
        db_connection=con,
        locale='en_US')
```
If I am running the same report in Jasper Studio 6.6.0, I am getting aroung 34 rows of valid data. But when I run the above code I just get Null as values in one row.

What could be the issue?

**Comment by varun952** [comment]
I will be looking forward to that sir, thank you

**Comment by jadsonbr** [comment]
Sorry, we won't support the mongo for now.

[No support](https://github.com/PyReportJasper/pyreportjasper#no-support)
