### ISSUE TITLE
Error filling reportError executing SQL statement for: test1.

### ISSUE THREAD

**Issue by KellyRDC** [PyReportJasper/pyreportjasper#46]
I'm getting an error of **Error filling reportError executing SQL statement for: test1.** with the code below.
The required jar file is in the **jdbc** folder.
And my db credentials is correct.

```
# -*- coding: utf-8 -*-
import os
from platform import python_version
from pyreportjasper import JasperPy

def advanced_example_using_database():

    input_file = '~/JaspersoftWorkspace/MyReports/test1.jrxml'

    output = os.path.dirname(os.path.abspath(__file__)) # + '/output/examples'
    con = {
        'driver': 'generic',
        'username': 'username',
        'password': 'password',
        'jdbc_url': 'jdbc:sqlserver://localhost:1433;databaseName=testdb',
        'jdbc_driver': 'net.sourceforge.jtds.jdbc.Driver'

    }
    jasper = JasperPy()

    jasper.process(
        input_file,
        output_file=output,
        format_list=["pdf"], # format_list=["pdf", "rtf", "xml"],
        parameters={},
        db_connection=con,
        locale='en_US'  # LOCALE Ex.:(en_US, de_GE, pt_BR)
    )

advanced_example_using_database()
```

**Comment by jadsonbr** [comment]
Please inform us the error that was generated in the whole console

**Comment by KellyRDC** [comment]
I'm only getting a message like this:

"Error filling reportError executing SQL statement for: test1"

Nothing else.

**Comment by jadsonbr** [comment]
@KellyRDC Has the issue been resolved?

**Comment by morizbebenk** [comment]
I had this one, but when I used jasperstarter command in Windows working fine, but in Ubuntu show error like that.
I use same jdbc driver btw.

**Comment by jadsonbr** [comment]
Download the JDBC driver from this page [Microsoft](https://docs.microsoft.com/pt-br/sql/connect/jdbc/working-with-a-connection?view=sql-server-ver15) and use the jdbc_driver "com.microsoft.sqlserver.jdbc.SQLServerDriver"
