### ISSUE TITLE
java.sql.Date Error

### ISSUE THREAD

**Issue by BlasFerna** [PyReportJasper/pyreportjasper#47]
I'am try to execute my report and get this error:

Parameter 'P_FILTRO_FECHA' of type 'java.sql.Date with value '2019-01-16' is not
 supported by JasperStarter!

**Comment by jadsonbr** [comment]
The Parameter that is as Date today changes to String and within the report convert to Date.

Jasper has problems passing Date as a parameter.

See more at:
[Issue Problem with Parameter type Date](https://community.jaspersoft.com/questions/515710/problem-parameter-type-date)

**Comment by BlasFerna** [comment]
My solution was sent the date as string and in the report i use sql function to change the type string to date. Thanks for your help!
