### ISSUE TITLE
Documentation: Instructions required on how to use CSV datasource

### ISSUE THREAD

**Issue by narenvema** [PyReportJasper/pyreportjasper#48]
Hi Team, 

The module is very helpful and easy to use, but i'll need instructions or documentation on how to use CSV data sources for PDF generation, request you to please support. 

Thank You.

**Comment by jadsonbr** [comment]
Added in master branch readme.
[Documentation Link](https://github.com/PyReportJasper/pyreportjasper#reports-from-a-csv-file)

**Comment by jadsonbr** [comment]
@narenvema 
Already managed to use?

**Comment by narenvema** [comment]
@jadsonbr 
Thanks a lot, but I figured it out then itself.
