### ISSUE TITLE
Chamada pelo Odoo

### ISSUE THREAD

**Issue by wallacemuniz** [PyReportJasper/pyreportjasper#49]
Saudações!
Estou tentando gerar o relatório através do Odoo, sistema operacional Windows10.
Apenas relatórios simples sem parâmetros ou conexão com banco de dados são impressos. 
Testes mais elaborados apresentam erros em jasperpy.py:
                logger.exception(str(e))
                raise NameError('Your report has an error and couldn '
                                r'\'t be processed!\ Try to output the '
                                'command using the attribute `command;` '
                                'and run it manually in the console!')

Porém, executando-se o comando diretamente pelo prompt os arquivos são gerados.
Acredito que seja erro de permissão de criação/leitura de arquivos.

Obrigado.

**Comment by jadsonbr** [comment]
Deu permissão de leitura e escrita na pasta do pacote ?
Se estiver utilizando o JRXML terá que dar permissão no local da compilação do relatório também.

**Comment by wallacemuniz** [comment]
Permissões concedidas aos diretórios principais e herdados para os filhos tanto da instalação do Odoo quanto ao Python37.
Testando relatório com banco de dados e parâmetros = mesmo erro.
Testando outro relatório sem parâmetros = pdf gerado.
Testando relatório com banco de dados e parâmetros, mas sem os sub reports = pdf gerado.
Vou investigar o que pode ser a causa desse problema.
Obrigado.

Obs... tive que alterar uma linha no jasperpy para aceitar parâmetros com tipo diferente de string.
