### ISSUE TITLE
Example for SQL Server

### ISSUE THREAD

**Issue by BonaDenyS** [PyReportJasper/pyreportjasper#51]
would you gimme example for sqlserver database setting pls?

**Comment by BonaDenyS** [comment]
I have do this, but is not working, and still error
`output = os.path.dirname(os.path.abspath(__file__)) + '/output/examples'
    con = {
        'driver': 'generic',
        'jdbc_driver': 'com.microsoft.sqlserver.jdbc.SQLServerDriver',
        'jdbc_url': 'jdbc:sqlserver://localhost:1433/mydatabase',
         'jdbc_dir': 'E:/Medisimed/NewDjangoApp/venv/Lib/site-packages/pyjasper/jasperstarter/jdbc/sqljdbc_6.0/enu/jre8'
    }
    jasper = JasperPy()
    jasper.process(
        input_file,
        output_file=output,
        format_list=["pdf", "rtf", "xml"],
        # parameters={'python_version': python_version()},
        db_connection=con,
        resource='E:/Medisimed/NewDjangoApp/venv/Lib/site-packages/pyjasper/jasperstarter/jdbc/sqljdbc_6.0/enu/jre8/sqljdbc42.jar',
        locale='en_US'  # LOCALE Ex.:(en_US, de_GE)
    )`

and it's still error like this

`ERROR:pyreportjasper.jasperpy:Command 'E:\Medisimed\NewDjangoApp\venv\lib\site-packages\pyreportjasper/jasperstarter/bin/jasperstarter --locale en_US process "E:\Medisimed\NewDjangoApp\SIM-RS\Leaf_Red.jrxml" -o "E:\Medisimed\NewDjangoApp\SIM-RS/output/examples" -f pdf rtf xml -t generic --db-driver com.microsoft.sqlserver.jdbc.SQLServerDriver --db-url
jdbc:sqlserver://localhost:1433/mydatabase--jdbc-dir E:/Medisimed/NewDjangoApp/venv/Lib/site-packages/pyjasper/jasperstarter/jdbc/sqljdbc_6.0/enu/jre8 -r E:/Medisimed/NewDjangoApp/venv/Lib/site-packages/pyjasper/jasperstarter/jdbc/sqljdbc_6.0/enu/jre8/sqljdbc42.jar' returned non-zero exit status 1.`

**Comment by jadsonbr** [comment]
@BonaDenyS Has the issue been resolved?

**Comment by jadsonbr** [comment]
Issue closed for lack of interaction.
