### ISSUE TITLE
Missing required option when using CSV file as datasource 

### ISSUE THREAD

**Issue by jwazne** [PyReportJasper/pyreportjasper#52]
Hello,

I'd like to use CSV file as datasource to produce a XLSX output file. 
I'm using the following syntax:
```
jasper = JasperPy()
    jasper.process(
        jasper_file,
        output_file=output_file,
        format_list=['xlsx'],
        db_connection={
            'data_file': 'mytest.csv',
            'driver': 'csv'
        },
        locale=jasper_locale,
        resource=jasper_folder)
```

However I'm stuck with the following error:
**jasperstarter: error: argument --csv-columns is required**

When running the jasperstarter command through the console **adding the required --csv-columns option**, it works. 

Where could I add the --csv-columns option using the pyreportjasper library ?

Thanks for your help.

Julien

**Comment by jadsonbr** [comment]
Thank you for contacting us.
After analysis we found that the parameter to add --csv-columns is missing.
We will be submitting as soon as possible this correction.

**Comment by jwazne** [comment]
Thanks @jadsonbr, I used json data file as workaround but the csv fix will be appreciated !

**Comment by jadsonbr** [comment]
Routine added to master branch

**Comment by jadsonbr** [comment]
@jwazne 
Already managed to use?

**Comment by jwazne** [comment]
@jadsonbr :Thank you. I'll finally keep using the json format as it is now working fine on production environment. However I might use the CSV format in my next applications. I will let you know of the outcome. Thanks again for your support.

**Comment by jadsonbr** [comment]
Needing to contact. See you.
