### ISSUE TITLE
connection to cassandra

### ISSUE THREAD

**Issue by rajeshkalluri009** [PyReportJasper/pyreportjasper#56]
Hi,
can i connect to cassandra?

**Comment by jadsonbr** [comment]
If you have JDBC drive yes.
But I didn't do any tests.
If successful let us know.

**Comment by jadsonbr** [comment]
@rajeshkalluri009 If resolved, please close the issue.

**Comment by jadsonbr** [comment]
Issue closed for lack of interaction.
