### ISSUE TITLE
Virtualizer

### ISSUE THREAD

**Issue by WesleyFreitas472** [PyReportJasper/pyreportjasper#58]
When i try to generate large reports, i'm getting the error "gc overhead limit exceeded jasper reports".

I read something about virtualizer to generate large reports.

How do i use virtualizer with jasperstarter/pyreportjasper?

**Comment by jadsonbr** [comment]
"The GC throws this exception when too much time is spent in garbage collection for too little return, eg. 98% of CPU time is spent on GC and less than 2% of heap is recovered.

These links can help you.
- [Help 1](https://community.jaspersoft.com/questions/980656/how-handle-huge-data-jasper-ireports)
- [Help 2](https://community.jaspersoft.com/wiki/virtualizers-jasperreports)
- [About the error](https://www.oracle.com/technetwork/java/javase/gc-tuning-6-140523.html#par%5Fgc.oom)

I also advise to use version 2 of this library as it has better performance and direct access to the jasperstarter api
[PyReportJasper2](https://github.com/PyReportJasper/pyreportjasper2)

**Comment by WesleyFreitas472** [comment]
I tryed to use PyReportJasper2 but aways get "Error: java.lang.IllegalArgumentException: Unable to load driver: com.mysql.jdbc.Driver".

Anyway, i need to use virtualizer with PyReportJasper. Is that possible? If yes, how?

**Comment by jadsonbr** [comment]
The question about the drive is because you didn't pass the mysql JDBC connection jar into the resource.

About the virtualizer I have no idea if it works or not.

**Comment by jadsonbr** [comment]
@WesleyFreitas472 If resolved, please close the issue.
