### ISSUE TITLE
Failed to pass a directory as a parameter.

### ISSUE THREAD

**Issue by willynpi** [PyReportJasper/pyreportjasper#59]
Hello, I was working on subreport and it failed to find the subreport when generating the PDF. I found a solution is to define the directory of the subreport as a parameter.
```XML
 <subreportExpression><![CDATA[$P{subReport} + 'subreport.jasper']]></subreportExpression>
```
It still failed at first attempt so I verify all my paths and parameters to see if they are all correct, directly from the command line. I found that it failed because the parameters are sent with quotation marks and I think it is not necessary to have. But I haven't tried other types of data like the timestamp mentioned in #57, just a suggestion from what I have encountered.

**Comment by jadsonbr** [comment]
@willynpi 
For the subreport to work you have to pass in the resource parameter the directory where it is located.
You can find an example of how to use subreport in the documentation. [Link](https://github.com/PyReportJasper/pyreportjasper#subreport-example)

To pass a datetime parameter, you must send it as String and do the conversion inside the report if necessary.

**Comment by jadsonbr** [comment]
@willynpi If resolved, please close the issue.

**Comment by jadsonbr** [comment]
Issue closed for lack of interaction.
