### ISSUE TITLE
Impossible to set Locale to JSON_LOCALE

### ISSUE THREAD

**Issue by frsc95** [PyReportJasper/pyreportjasper#60]
I have a big trouble when it comes to process JSON file, I could process nicely lots of different data in that JSON. But... when it comes to real numbers such as 3.123 my report represents that data as an Integer even thought I set the field settiog to a (Double, Float, BigDecimal...) all them interprets them as an Integer like 3123 ... Doing bit of research I figured out that when I pass the  locale "es_ES" , in my case I need to format the report en spanish localization.
I realized that the JSON_LOCALE  that is a parameter configuration related to the driver of the json adapter setted in the Jasper.process(...) method sets "es_ES" globally. The fact is that I really need to modify the JSON_LOCALE parameter to allow the report to interpret correctly the JSON floating numbers. Also, I should avoid to use "en_US" Locale globally, only set it at the JSON_LOCALE parameter.

I hope you can fix this Issue. I wouldd be very thanked.

**Comment by jadsonbr** [comment]
Could you tell me if it happens with version 2 of the library?

[pyreportjasper2](https://github.com/PyReportJasper/pyreportjasper2)

**Comment by jadsonbr** [comment]
@frsc95 

We created a specific method to deal with JSON data source.
Take a look and see if it meets your need.

[See the documentation here](https://github.com/PyReportJasper/pyreportjasper/wiki/Reports-from-a-JSON)

**Comment by jadsonbr** [comment]
@frsc95 If resolved, please close the issue.
