### ISSUE TITLE
NameError: Error: java.lang.IllegalArgumentException: Unable to load driver: com.mysql.jdbc.Driver

### ISSUE THREAD

**Issue by hanggaga** [PyReportJasper/pyreportjasper#61]
I stuck at the error above. I do not know how to add the driver MySQL under the directory JDBC

jdbc
 - mysql.jar ** mine
 - postgressql.jar
 - README
is the name of the file incorrect?

**Comment by jadsonbr** [comment]
@hanggaga You can pass your JDBC jar as a resource.

[See the example in the documentation](https://github.com/PyReportJasper/pyreportjasper/wiki/Working-with-resources)

**Comment by hanggaga** [comment]
Thank you for your reply. This is my code that still come up the same error
```
def advanced_example_using_database(request):
    file_name = 'jasper'
    input_file_name = '{}.jrxml'.format(file_name)
    input_file_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'files', input_file_name)
    driver = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'jdbc', 'postgresql-42.2.14.jar')
    con = {
        'driver': 'postgres',
        'username': 'DB_USERNAME',
        'password': 'DB_PASSWORD',
        'host': 'DB_HOST',
        'database': 'DB_DATABASE',
        'schema': 'DB_SCHEMA',
        'port': '5432'
    }
    jasper = JasperPy()
    jasper.process(
        input_file_path,
        format_list=["pdf"],
        parameters={},
        db_connection=con,
        locale='en_US',
        resource=driver
    )

![image](https://user-images.githubusercontent.com/40156400/84355922-a0b47000-abed-11ea-8108-68e259f545fe.png)

**Comment by jadsonbr** [comment]
@hanggaga We actually found a bug in the library that prevents connection to the database.

I recommend using version 1 until this is resolved. To do this, just change the import.
```python
from pyreportjasper import JasperPy1
```

**Comment by jadsonbr** [comment]
@hanggaga Problem solved in the new version.
Please disregard the previous comment. The JasperPy1 class has been removed in this release.

**Comment by jadsonbr** [comment]
Issue closed for lack of interaction.
