### ISSUE TITLE
Error to Install

### ISSUE THREAD

**Issue by rangeltorrezan** [PyReportJasper/pyreportjasper#62]
Hi, I'm trying install and got this error:

>  Using cached jpy-0.7.5.zip (144 kB)
>     ERROR: Command errored out with exit status 1:
>      command: /Users/rangeltorrezan/Desktop/KeepsDev/workspace/KeepsReports/.virtualenvs/report-keeps/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-ycwfl3f1/jpy/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-ycwfl3f1/jpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/tmp/pip-pip-egg-info-nzqyo9rs
>          cwd: /private/tmp/pip-install-ycwfl3f1/jpy/
>     Complete output (6 lines):
>     Building a 64-bit library for a Darwin system
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/private/tmp/pip-install-ycwfl3f1/jpy/setup.py", line 100, in <module>
>         with open('README.rst') as file:
>     FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> 

I try install with pip instal, downloading the package and using setup install, with root, with user ... anyway ..

I'm using MacOS but I tried in other device with Ubuntu.

**Comment by jadsonbr** [comment]
@rangeltorrezan Run the command below

```
pip install git+https://github.com/bcdev/jpy@master#egg=jpy
```

**Comment by rangeltorrezan** [comment]
Works!

Tks.

**Comment by jadsonbr** [comment]
@rangeltorrezan If resolved, please close the issue.
