### ISSUE TITLE
Cannot pip install 

### ISSUE THREAD

**Issue by nikith77** [PyReportJasper/pyreportjasper#63]
Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\xxx\AppData\Local\Temp\pip-install-cay4d0h_\jpy\setup.py", line 100, in <module>
        with open('README.rst') as file:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
    Building a 64-bit library for a Windows system
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by jadsonbr** [comment]
@nikith77 Run the command below

```
pip install git+https://github.com/bcdev/jpy@master#egg=jpy
```

**Comment by nikith77** [comment]
thanks Jadsonbr..

Getting this error.
  

  Running setup.py install for jpy ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\xxx\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-install-opj0ik4u\\jpy\\setup.py'"'"'; __file__='"'"'C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-install-opj0ik4u\\jpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\xxx\AppData\Local\Temp\pip-record-59x9_oyv\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Include\jpy'
         cwd: C:\Users\xxx\AppData\Local\Temp\pip-install-opj0ik4u\jpy\
    Complete output (9 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    copying jpyutil.py -> build\lib.win-amd64-3.8
    running build_ext
    building 'jpy' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\xxx\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-install-opj0ik4u\\jpy\\setup.py'"'"'; __file__='"'"'C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-install-opj0ik4u\\jpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\xxx\AppData\Local\Temp\pip-record-59x9_oyv\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Include\jpy' Check the logs for full command output.

**Comment by jadsonbr** [comment]
@nikith77 The exception itself is already shown the cause

Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio"
https://visualstudio.microsoft.com/downloads/

**Comment by nikith77** [comment]
error: [Errno 2] No such file or directory: 'mvn'

**Comment by jadsonbr** [comment]
@nikith77 Maven is a requirement
https://github.com/PyReportJasper/pyreportjasper#requirements

**Comment by humbertolopezleon** [comment]
> @nikith77 Run the command below
> 
> ```
> pip install git+https://github.com/bcdev/jpy@master#egg=jpy
> ```

Why is it necessary to install it from Github? It would be very convenient to be able to install **Pyreportjasper** using `pip install pyreportjasper`.

**Comment by jadsonbr** [comment]
Yes correct. Today the library is out of date in the **pypi** but the new version will surely be there. This command you mentioned above refers to a dependency on the library we are working on to remove it
