### ISSUE TITLE
can not pip install git+https://github.com/bcdev/jpy@master#egg=jpy

### ISSUE THREAD

**Issue by jmarco** [PyReportJasper/pyreportjasper#65]
I can not install:  pip install git+https://github.com/bcdev/jpy@master#egg=jpy

Enviroment:

Maven:
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\archivos\Programacion\tools\apache-maven-3.6.3-bin\bin\..
Java version: 1.8.0_261, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_261\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

Microsoft Visual Studio 14.0:
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin

Error:
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO "/LIBPATH:C:\Program Files\Java\jdk1.8.0_261\jre\bin\server" "/LIBPATH:C:\Program Files\Java\jdk1.8.0_261\lib" /LIBPATH:c:\archivos\programacion\virtualenvs\nemesis\env\libs /LIBPATH:C:\Users\jmarco\AppData\Local\Programs\Python\Python38-32\libs /LIBPATH:C:\Users\jmarco\AppData\Local\Programs\Python\Python38-32 /LIBPATH:c:\archivos\programacion\virtualenvs\nemesis\env\PCbuild\win32 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x86" jvm.lib /EXPORT:PyInit_jpy build\temp.win32-3.8\Release\src\main\c\jpy_module.obj build\temp.win32-3.8\Release\src\main\c\jpy_diag.obj build\temp.win32-3.8\Release\src\main\c\jpy_verboseexcept.obj build\temp.win32-3.8\Release\src\main\c\jpy_conv.obj build\temp.win32-3.8\Release\src\main\c\jpy_compat.obj build\temp.win32-3.8\Release\src\main\c\jpy_jtype.obj build\temp.win32-3.8\Release\src\main\c\jpy_jarray.obj build\temp.win32-3.8\Release\src\main\c\jpy_jobj.obj build\temp.win32-3.8\Release\src\main\c\jpy_jmethod.obj build\temp.win32-3.8\Release\src\main\c\jpy_jfield.obj build\temp.win32-3.8\Release\src\main\c\jni/org_jpy_PyLib.obj /OUT:build\lib.win32-3.8\jpy.cp38-win32.pyd /IMPLIB:build\temp.win32-3.8\Release\src\main\c\jpy.cp38-win32.lib
       Creating library build\temp.win32-3.8\Release\src\main\c\jpy.cp38-win32.lib and object build\temp.win32-3.8\Release\src\main\c\jpy.cp38-win32.exp
    jpy_module.obj : error LNK2001: unresolved external symbol __imp__JNI_CreateJavaVM@12
    build\lib.win32-3.8\jpy.cp38-win32.pyd : fatal error LNK1120: 1 unresolved externals
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\link.exe' failed with exit status 1120

Thks

**Comment by jadsonbr** [comment]
@jmarco Try to compile with source code. And then install with the wheel

[how to build a wheel for windows](https://github.com/bcdev/jpy#how-to-build-a-wheel-for-windows)

**Comment by jmarco** [comment]
I have the same result

Error, building 'jpy' extension
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h(1764): note: see declaration of 'sprintf'
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO "/LIBPATH:C:\Program Files\Java\jdk1.8.0_261\jre\bin\server" "/LIBPATH:C:\Program Files\Java\jdk1.8.0_261\lib" /LIBPATH:C:\archivos\Programacion\virtualenvs\Nemesis\env\libs /LIBPATH:C:\Users\jmarco\AppData\Local\Programs\Python\Python38-32\libs /LIBPATH:C:\Users\jmarco\AppData\Local\Programs\Python\Python38-32 /LIBPATH:C:\archivos\Programacion\virtualenvs\Nemesis\env\PCbuild\win32 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x86" jvm.lib /EXPORT:PyInit_jpy build\temp.win32-3.8\Release\src\main\c\jpy_module.obj build\temp.win32-3.8\Release\src\main\c\jpy_diag.obj build\temp.win32-3.8\Release\src\main\c\jpy_verboseexcept.obj build\temp.win32-3.8\Release\src\main\c\jpy_conv.obj build\temp.win32-3.8\Release\src\main\c\jpy_compat.obj build\temp.win32-3.8\Release\src\main\c\jpy_jtype.obj build\temp.win32-3.8\Release\src\main\c\jpy_jarray.obj build\temp.win32-3.8\Release\src\main\c\jpy_jobj.obj build\temp.win32-3.8\Release\src\main\c\jpy_jmethod.obj build\temp.win32-3.8\Release\src\main\c\jpy_jfield.obj build\temp.win32-3.8\Release\src\main\c\jni/org_jpy_PyLib.obj /OUT:build\lib.win32-3.8\jpy.cp38-win32.pyd /IMPLIB:build\temp.win32-3.8\Release\src\main\c\jpy.cp38-win32.lib
   Creating library build\temp.win32-3.8\Release\src\main\c\jpy.cp38-win32.lib and object build\temp.win32-3.8\Release\src\main\c\jpy.cp38-win32.exp
jpy_module.obj : error LNK2001: unresolved external symbol __imp__JNI_CreateJavaVM@12
build\lib.win32-3.8\jpy.cp38-win32.pyd : fatal error LNK1120: 1 unresolved externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\link.exe' failed with exit status 1120

Environment Variables:
VS100COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_261
JDK_HOME=C:\Program Files\Java\jdk1.8.0_261

Thks

**Comment by jadsonbr** [comment]
@jmarco I advise you to open an issue in [jpy](https://github.com/bcdev/jpy) as this is an error regarding the compilation of a dependency on pyreportjasper and not pyreportjasper.

**Comment by jadsonbr** [comment]
Issue closed for lack of interaction.
