### ISSUE TITLE
ImportError: DLL load failed while importing jpy: The specified module could not be found

### ISSUE THREAD

**Issue by davidlehrian** [PyReportJasper/pyreportjasper#68]
Hello, first let me say thank you for doing this project.  I have used JasperReports for years in Java projects and now need a robust reporting solution for a Python project.  I have worked through all the kinks in getting it running with OpenJDK 15 and have submitted my change to the jasperstarter project to allow it to work with OpenJDK 15.  This is the final issue I came across.  

As I was attempting to run my first jasper report from Python 3.8 via the "Advanced example - using a database" at https://pypi.org/project/pyreportjasper/ I encountered the error "ImportError: DLL load failed while importing jpy: The specified module could not be found".  I discovered this is because the jvm needs to be initialized prior to importing jpy.  This does not appear to be specific to OpenJDK 15 as I came across this post https://stackoverflow.com/questions/63953649/how-to-resolve-this-pyreportjasper-importerror-dll-load-failed-while-importin/64348967#64348967 in which the poster is using JDK 1.8.0_261.  I was able to fix this error by moving the import jpy statement from line 14 to line 56 and am now able to run the example code and fill a Jasper Report from Python 3.8.  Here is the pertinent change to the file.  

```
# -*- coding: utf-8 -*-
# GNU GENERAL PUBLIC LICENSE
#
# Copyright (c) 2020 Jadson Bonfim Ribeiro <contato@jadsonbr.com.br>
#

import os
import subprocess
import re
import xml.etree.ElementTree as ET

import tempfile
import jpyutil
#import jpy
import json
from requests import Request, Session

FORMATS = (
    'pdf',
    'rtf',
    'xls',
    'xlsx',
    'docx',
    'odt',
    'ods',
    'pptx',
    'csv',
    'html',
    'xhtml',
    'xml',
    'jrprint',
)

EXECUTABLE = 'jasperstarter'

class JasperPy:

    _FORMATS_JSON = ('pdf')

    _FORMATS_METHODS_REQUEST = ('GET', 'POST', 'PUT')

    def __init__(self, resource_dir=False, jvm_maxmem='512M', jvm_classpath=None):
        self.WINDOWS = True if os.name == 'nt' else False
        self.SCRIPT_DIR = os.path.abspath(os.path.dirname(__file__))
        self.LIBS = os.path.join(self.SCRIPT_DIR, 'jasperstarter', 'lib')
        if not os.path.isdir(self.LIBS):
            raise NameError('Unable to find lib in {0}'.format(self.LIBS))
        self.CLASSPATH = os.path.join(self.LIBS, 'jasperstarter.jar')
        if not os.path.exists(self.CLASSPATH):
            raise NameError('Unable to find jasperstarter in {0}'.format(self.LIBS))
        if jvm_classpath is None:
            jpyutil.init_jvm(jvm_maxmem=jvm_maxmem, jvm_classpath=[self.CLASSPATH])
        else:
            jpyutil.init_jvm(jvm_maxmem=jvm_maxmem, jvm_classpath=[self.CLASSPATH, jvm_classpath])
        # IMPORT jpy HERE AFTER init_jvm
        import jpy
        self.jvFile = jpy.get_type('java.io.File')
        self.jvArrays = jpy.get_type('java.util.Arrays')
        self.jvReport = jpy.get_type('de.cenote.jasperstarter.Report')
        self.jvConfig = jpy.get_type('de.cenote.jasperstarter.Config')
        self.jvDsType = jpy.get_type('de.cenote.jasperstarter.types.DsType')
        self.jvApplicationClasspath = jpy.get_type('de.cenote.tools.classpath.ApplicationClasspath')
        self.jvHashMap = jpy.get_type('java.util.HashMap')
        self.jvLocale = jpy.get_type('java.util.Locale')
        self.jvJasperFillManager = jpy.get_type('net.sf.jasperreports.engine.JasperFillManager')
        self.jvDb = jpy.get_type('de.cenote.jasperstarter.Db')
        self.jvJsonQueryExecuterFactory = jpy.get_type('net.sf.jasperreports.engine.query.JsonQueryExecuterFactory')
        self.jvJasperExportManager = jpy.get_type('net.sf.jasperreports.engine.JasperExportManager')
.
.
.

```

**Comment by jadsonbr** [comment]
@davidlehrian We would be happy to accept your PR on this matter.

**Comment by davidlehrian** [comment]
@jadsonbr I submitted a PR for this change which is a simple fix.  

I have additional changes to pyreportjasper that allow jasperstarter to work with Open JDK 15 and I have submitted a PR to them for these changes but they have not yet responded.  So my branch https://github.com/davidlehrian/pyreportjasper/tree/open_jdk15 includes a custom version of jasperstarter.jar (as well as JasperReports 6.15.0) .   

It also includes pyjasperreports.py which has code to compile, fill and output jasper reports in a variety of formats without needing to spawn a system process via jasperstarter which runs much more quickly than JasperPy.process.  This code does not rely on Open JDK 15 but as I don't have the older JDK 1.8 installed I can't test against it.  

I can submit a pull request for this as well, but I'm not sure if that is reasonable as it includes a custom compile of  https://bitbucket.org/dlehrian/jasperstarter/src/fix_for_URLClassLoader/ which has not yet been accepted into the master branch.

**Comment by jadsonbr** [comment]
@davidlehrian We can do this in a different branch to do the tests and then merge it to the main

[I created the JDK_15 branch for this](https://github.com/PyReportJasper/pyreportjasper/tree/jdk_15)

**Comment by davidlehrian** [comment]
OK, I will figure out how to swap my branch head for [open_jdk15](https://github.com/davidlehrian/pyreportjasper/tree/open_jdk15 ) to point to [JDK_15](https://github.com/PyReportJasper/pyreportjasper/tree/jdk_15) and submit a PR.

**Comment by jadsonbr** [comment]
@davidlehrian you just need to create a PR comparing your branch with what I created now

Something like that
[https://github.com/PyReportJasper/pyreportjasper/compare/jdk_15...davidlehrian:open_jdk15](https://github.com/PyReportJasper/pyreportjasper/compare/jdk_15...davidlehrian:open_jdk15)

**Comment by davidlehrian** [comment]
Thanks for doing that for me.  I'm not sure exactly how you did that, but thank you.  I have to run for the afternoon but will look at exactly what you did this evening.  I'm new to GIT and don't have all the local/remote/origin thing down yet.
