### ISSUE TITLE
How to use subdataset with JSON

### ISSUE THREAD

**Issue by nikola-v** [PyReportJasper/pyreportjasper#69]
Hi,

I have JSON source which contains multiple information for different charts and tables and I would like to select separate subdatasets for different charts.

Also I have tried to add data adapter which works fine in Jaspersoft studio but when run from console it generates error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyreportjasper-2.0.2-py3.8.egg/pyreportjasper/jasperpy.py", line 364, in process_json
    jasperPrint = self.jvJasperFillManager.fillReport(file_out, parameters, ds)
RuntimeError: java.lang.NoClassDefFoundError: org/apache/http/HttpEntity

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyreportjasper-2.0.2-py3.8.egg/pyreportjasper/jasperpy.py", line 369, in process_json
    raise NameError('Error: %s' % str(e))
NameError: Error: java.lang.NoClassDefFoundError: org/apache/http/HttpEntity

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "from_JSON.py", line 40, in <module>
    json_to_pdf()
  File "from_JSON.py", line 16, in json_to_pdf
    jasper.process_json(
  File "/usr/local/lib/python3.8/dist-packages/pyreportjasper-2.0.2-py3.8.egg/pyreportjasper/jasperpy.py", line 373, in process_json
    raise NameError('Error: %s' % str(e))
NameError: Error: Error: java.lang.NoClassDefFoundError: org/apache/http/HttpEntity
```

BR!

**Comment by jadsonbr** [comment]
@nikola-v The above error occurs because in your report you are using a non-native jasper library. To resolve, download the library and pass it as a resource to the report.

[Working with resources](https://github.com/PyReportJasper/pyreportjasper/wiki/Working-with-resources)

**Comment by nikola-v** [comment]
@jadsonbr From the message it looks like Apache http client is missing ( just my guess), so I should add jar files as resources? Is there any example on how to load resources maybe.

**Comment by jadsonbr** [comment]
@nikola-v  [Working with resources](https://github.com/PyReportJasper/pyreportjasper/wiki/Working-with-resources)

**Comment by nikola-v** [comment]
@jadsonbr Thank you for your help! It seems that it is error from missing class. I would like to use Data Adapter, but no matter what I add as resource jasperstarter wants to use HttpClient and it cannot be found. Is there any example for using Data Adapter in pyreportjasper?

**Comment by jadsonbr** [comment]
@nikola-v We use Jasperstarter as an intermediary for handling JasperReport and it has this limitation. All subreports must use the same data source as the main report.

[To learn more, click here](http://jasperstarter.cenote.de/usage.html#Reports_with_Subreports)

**Comment by jadsonbr** [comment]
Issue closed for lack of interaction.
